{% set version = "7.4.1" %}

package:
  name: bazel
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
  sha256: 83386618bc489f4da36266ef2620ec64a526c686cf07041332caff7c953afaf5
  patches:
    - patches/0001-allow-args-to-be-passed-to-bazel_build.patch          # [unix]
    - patches/0006-missing_inttype_h.patch                               # [unix]

build:
  number: 0
  ignore_prefix_files: True
  binary_relocation: False  # [osx]
  ignore_run_exports:
    - libcxx # [not osx]
  missing_dso_whitelist:
    - "*/libc++.1.dylib" # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain
    - patch  # [unix]
    - python
  host:
    - openjdk 21
    - posix  # [win]
    - unzip  # [linux]
    - zip    # [linux]
  run:
    - openjdk >=21
    - posix  # [win]

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain
  # Test commands are in run_test.sh and run_test.bat

about:
  home: https://bazel.build/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: build system originally authored by Google
  description: |
    Bazel is Google's own build tool, now publicly available in Beta. Bazel has
    built-in support for building both client and server software, including
    client applications for both Android and iOS platforms. It also provides an
    extensible framework that you can use to develop your own build rules.
  dev_url: https://github.com/bazelbuild/bazel
  doc_url: https://bazel.build/docs

extra:
  recipe-maintainers:
    - jjhelmus
    - nehaljwani
    - xhochy
