{% set version = "5.4.1" %}

package:
  name: bazel
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
  sha256: dcff6935756aa7aca4fc569bb2bd26e1537f0b1f6d1bda5f2b200fa835cc507f
  patches:
    - patches/0001-allow-args-to-be-passed-to-bazel_build.patch  # [unix]
    - patches/0002-do-not-use-enable-gold-unless-supported.patch  # [unix]
    - patches/0004-link-against-iokit.patch  # [osx]
    - patches/0005-fix_netrc_protocol.patch  # [osx]
    - patches/0006-missing_inttype_h.patch
    - patches/0007-patch2.patch

build:
  number: 0
  # Missing OpenJDK >= 8 on s390x and ppc64le.
  skip: True  # [s390x or ppc64le]
  ignore_prefix_files: True
  binary_relocation: False  # [osx]
  ignore_run_exports:
    - libcxx # [not osx]
  missing_dso_whitelist:
    - "*/libc++.1.dylib" # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch  # [unix]
    - python
  host:
    - openjdk >=8
    - posix  # [win]
    - unzip  # [linux]
    - zip    # [linux]
  run:
    - openjdk >=8
    - posix  # [win]

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://bazel.build/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: build system originally authored by Google
  description: |
    Bazel is Google's own build tool, now publicly available in Beta. Bazel has
    built-in support for building both client and server software, including
    client applications for both Android and iOS platforms. It also provides an
    extensible framework that you can use to develop your own build rules.
  dev_url: https://github.com/bazelbuild/bazel
  doc_url: https://bazel.build/docs

extra:
  recipe-maintainers:
    - jjhelmus
    - nehaljwani
