{% set version = "5.3.1" %}

package:
  name: bazel
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
  sha256: 18486e7152ca26b26585e9b2a6f49f332b116310d3b7e5b70583f1f1f24bb8ae
  patches:
    - patches/0001-allow-args-to-be-passed-to-bazel_build.patch  # [unix]
    - patches/0002-do-not-use-enable-gold-unless-supported.patch  # [unix]
    - patches/0004-link-against-iokit.patch  # [osx]
    - patches/0005-fix_netrc_protocol.patch  # [osx]
    # - patches/0006-missing_inttype_h.patch
    - patches/0007-patch2.patch
    # - patches/0009-win-Disable-VS-activation-and-make-build-verbose.patch
    - patches/0010-directory-not-empty.patch
    
build:
  number: 0
  # trigger: 1
  # Missing OpenJDK >= 8 on s390x and ppc64le.
  skip: True  # [s390x or ppc64le or py<37]
  ignore_prefix_files: True
  binary_relocation: False  # [osx]
  ignore_run_exports:
    - libcxx # [not osx]
  missing_dso_whitelist:
    - "*/libc++.1.dylib" # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch  # [unix]
    - m2-patch  # [win]
    - python
  host:
    - openjdk >=8,<17
    - posix  # [win]
    - unzip  # [linux]
    - zip    # [linux]
    - wheel
    - setuptools
  run:
    - openjdk >=8,<17
    - posix  # [win]
    - ijar {{ version }}       # [build_platform != target_platform]
    - singlejar {{ version }}  # [build_platform != target_platform]
test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  commands:
    - bazel -h
    - readelf -d $PREFIX/bin/bazel  # [linux]
    - conda inspect linkages -p $PREFIX bazel # [unix]
    # manually check that -lstdc++ appears in the bundled unix_cc_configure.bzl
    # tar xf /path/to/pkgs/bazel-0.5.4-hf484d3e_0.tar.bz2 bin/bazel
    # unzip -p bin/bazel embedded_tools/tools/cpp/unix_cc_configure.bzl | grep stdc++

about:
  home: https://bazel.build/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: build system originally authored by Google
  description: |
    Bazel is Google's own build tool, now publicly available in Beta. Bazel has
    built-in support for building both client and server software, including
    client applications for both Android and iOS platforms. It also provides an
    extensible framework that you can use to develop your own build rules.
  dev_url: https://github.com/bazelbuild/bazel
  doc_url: https://bazel.build/docs

extra:
  recipe-maintainers:
    - h-vetinari
    - nehaljwani
    - abhi18av
    - jschueller
    - adrianchia
    - xhochy