{% set version = "0.5.4" %}

package:
  name: bazel
  version: {{ version }}

source:
  url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
  sha256: 2157b05309614d6af0e4bbc6065987aede590822634a0522161f3af5d647abc9
  patches:
    - xcode_locator.patch  # [osx]
    - 0001-do-not-include-B-usr-bin.patch  # [linux]
    - 0002-allow-args-to-be-passed-to-bazel_build.patch
    # apply statically link libstd++ patch in build.sh
    #- 0003-statically-link-libstdc.patch
    - 0004-unpatched-unix_cc_configure.bzl-in-embedded-tools.patch

build:
  number: 0
  ignore_prefix_files: True
  skip: True  # [win]
  skip: True  # [linux32]
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch
  host:
    - openjdk >=8
    - unzip  # [linux]
    - zip    # [linux]
  run:
    - openjdk >=8

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  commands:
    - bazel -h
    - readelf -d $PREFIX/bin/bazel
    # manually check that -lstdc++ appears in the bundled unix_cc_configure.bzl
    # tar xf /path/to/pkgs/bazel-0.5.4-hf484d3e_0.tar.bz2 bin/bazel
    # unzip -p bin/bazel embedded_tools/tools/cpp/unix_cc_configure.bzl | grep stdc++

about:
  home: https://www.bazel.io/
  summary: build system originally authored by Google
  description: |
    Bazel is Google's own build tool, now publicly available in Beta. Bazel has
    built-in support for building both client and server software, including
    client applications for both Android and iOS platforms. It also provides an
    extensible framework that you can use to develop your own build rules.
  dev_url: https://github.com/bazelbuild/bazel
  doc_url: https://www.bazel.io/versions/master/docs/install.html
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jjhelmus
    - nehaljwani
