{% set version = "8.3.1" %}
{% set base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: bazel
  version: {{ version }}

source:
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: 79da863df05fa4de79a82c4f9d4e710766f040bc519fd8b184a4d4d51345d5ba
    patches:
      # bazel depends on https://github.com/conda-forge/singlejar-feedstock to build,
      # which patches the same sources; the patches from singlejar should either be
      # taken over here, or synced back if change is necessary
      - patches/0001-allow-args-to-be-passed-to-bazel_build.patch  # [unix]
      - patches/0002-Build-with-native-dependencies.patch          # [unix]
      - patches/0003-use-C-17.patch                                # [unix]
      - patches/0004-Use-conda-packages-for-build-tools.patch      # [unix]
      - patches/0005-grpc-java-plugin-from-build.patch             # [unix]
      - patches/0006-bazel-bin-loader-path.patch                   # [osx]
      - patches/0007-Adjust-cross-bazel-resultpath.patch           # [unix]
      - patches/0008-Install-protobuf-via-maven.patch              # [unix]
      - patches/0009-Adopt-system-libprotobuf.patch                # [unix]
      - patches/0010-Enable-new-protobuf-major-release.patch       # [unix]
      - patches/0011-Add-missing-absl-dependency.patch             # [unix]
      - patches/0012-Force-version-overrides-for-bazel-skylib-and-rules-cc.patch  # [unix]
      - patches/0013-Update-grpc-maven-artifacts-to-match.patch    # [unix]
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-windows-x86_64.exe  # [win]
    sha256: a3349d1d9e2327e03344c47244d4832ab14fc78142d050aa5599d85ee26b5f79  # [win]

build:
  number: 0
  ignore_prefix_files: True
  binary_relocation: False  # [osx]
  script_env:
    # The release timestamp of this version.
    - SOURCE_DATE_EPOCH="1751303700"  # 6/30/2025 1:15 PM EDT

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - msys2-sed                       # [win]
    - sed                             # [unix]
    - openjdk 21.*                    # [unix]
    # we need $BUILD_PREFIX/bin/{grpc_cpp_plugin,grpc_java_plugin,protoc}
    # lock to the same major.minor version as libgrpc
    - grpc_java_plugin {{ ".".join(libgrpc.split(".")[:2]) }}  # [unix]
    - libgrpc {{ libgrpc }}           # [unix]
    - libprotobuf {{ libprotobuf }}   # [unix]
    - ijar {{ version }}              # [unix]
    - singlejar {{ version }}         # [unix]
    - bazel-toolchain >=0.2.0         # [unix]
    - zip                             # [linux]
    - unzip                           # [linux]
    - python
    - pip
  host:
    - libabseil {{ libabseil }}      # [unix]
    - libgrpc {{ libgrpc }}          # [unix]
    - libprotobuf {{ libprotobuf }}  # [unix]
    - protobuf-bazel-rules {{ ".".join(libprotobuf.split(".")[1:]) }}  # [unix]
    - openjdk 21.*                   # [win]
    - msys2-posix 1                  # [win]
    - python
    - pip
  run:
    - openjdk >=21
    - msys2-posix              # [win]
    - ijar {{ version }}       # [unix]
    - singlejar {{ version }}  # [unix]

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain >=0.2    # [unix]
  commands:
    - bazel -h
    - bazel version

about:
  home: https://bazel.build/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: build system originally authored by Google
  description: |
    Bazel is Google's own build tool, now publicly available in Beta. Bazel has
    built-in support for building both client and server software, including
    client applications for both Android and iOS platforms. It also provides an
    extensible framework that you can use to develop your own build rules.
  dev_url: https://github.com/bazelbuild/bazel
  doc_url: https://bazel.build/docs

extra:
  skip-lints:
    - msys2_must_be_in_build  # The build tool posix is not in the build section.
    - has_run_test_and_commands
  recipe-maintainers:
    - h-vetinari
    - nehaljwani
    - abhi18av
    - jschueller
    - adrianchia
    - xhochy
