build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
test: native
bot:
  check_solvable: true
  abi_migration_branches:
    - 4.2.x
