travis:
  secure:
    BINSTAR_TOKEN: oXqAYPCwbXyJVwuXFRYMrgZdW8+AI56S74V/tRJllmwHufVl2wT191Fea0MCk8gfGPjeDCfFCd+y8DVcMFn2rnMmHxyz5UuHZKQyg/8JQjgPi3p7QF2vA1AtdVOW/V39jXCeGizU680cFDy2XnYy37yAeP9VOSyewJVdKTthBf9jgAoz4q9nzjdLIYaCijToQ56+7RPTM09wstR+czjiuATdbOSwtx1uR4BJbU+T+H7/KhUW+xYs08K5G454U6/56Q3b8rhlBSxv/s40TVK694qHpV6UEYOiZjzZkgaBuixqOCVQ9Fh8C6iGHIG8K4nQ6p+gKimMTD15Ju0CAG19Ti3+EkRXBhBw8pyqcHLRRgEUvpuNIcKcTp6oa31fzX/POExB5Fc9kfG5fDShERLy+xkVbFf+OlU8e4zRiOgvMwDrw5kMHYNe8a6gOXaLGDMkeWg0N9KDpgtItimUWsO4kIw+fwEPG+i2xSIN+C65f1uLxdmNn8Bt/nAeOAPA/h3woDk4MZ1Yf6PUm4wS1rutxnm/KOitIIdJcmBbUF/4ehGcLZijBk+xE3r3PsFzSsxbImqT38Xs1OrR+5IQ72ENGbLLpWMVQHoIOcbcxzkmJ2DKjq3A3+GsE05TdmPlbNykCTwgLJ6gUc25tVOMSRXs4P0Pgy95pCBP9W3MfXMrPVI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
