travis:
  secure:
    BINSTAR_TOKEN: Wb2DEsh69th83BJUFeoZfqiQ4VFdo756b/diJsDCVzJRB1LeprIMOUdqKNSWKEqfchio/zcKY7p3Eu2WniBaHgOCq41shFc8KY7kDKetyUO/sTJalnler6cZO99kZBScCsl04sNNtKDpr19y9nzzXrwRgzx7u9z7y7zNrMSmfROcvEaRtfF7uE4Ej6VduPHDh9I26w9kEx6dJNx1UHIUjDtbAXo+BcPFv2i6bwGHbHZmK04mMmQqrJQ+HwknYw3sbwTVV5VoA5qM8l/9bhWwMC3etV/K5V1QWRsrJUnX/geMon84yece7LF+Zoa97LX1B71C0eRzcSJyhdAEZDxi7eaf9mflkv9Vkjsg66637q1YjKOE6njMcXh8Cjjc62fLFxzmYf3nGnWoiAUgA7Y1aDFeXoSx0cL5tCxZKPJ4PSx9lUX9JR7/JebFcTViB7tccPCTjPA/gDUNOPTIztp8rT7Pw+es2hLGEFFYJKv5fVOYxrzQEYhmalfmIkmxCiC0wPKC1vGimhvclPItTmCfDtzxsPub449HHrKg7RW/BN+Sp94ubun//rsJl/nWrL8eNa0tJ+Bap7eD/YDwCHstXe1Dot/1YzLuFCo99nb4Nnq7lo6uqnmozBHDwFunlIPzaez4n/Tt8ab4sxdaljXCj5KtkMQvAlkQ/2yMzv542YQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
